In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
names = ["sepal-lentgh", "sepal-width", "petal-length", "petal-width", "classes"]
data_frame = pd.read_csv(url, names = names)

In [3]:
data_frame.head()

sepal-lentgh  sepal-width  petal-length  petal-width      classes
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [4]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal-lentgh  150 non-null    float64
 1   sepal-width   150 non-null    float64
 2   petal-length  150 non-null    float64
 3   petal-width   150 non-null    float64
 4   classes       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [5]:
x = data_frame.iloc[:,:-1]

In [6]:
y = data_frame.iloc[:,4]

In [7]:
from sklearn.model_selection import train_test_split
x_train , x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2)

In [8]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

In [9]:
import numpy as np
kn = 25
k_list = np.zeros((kn-1))

In [10]:
from sklearn.model_selection import cross_val_score

In [12]:
folds = 10
cvscore = []

In [13]:
len(x)*((folds-1)/folds)

135.0

In [14]:
k_list = list(range(1,int(len(x)*((folds-1)/folds))))

In [15]:
k_list

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134]

In [17]:
from sklearn.neighbors import KNeighborsClassifier

In [19]:
cvscore = []
for n in range(1,kn):
    neigh = KNeighborsClassifier(n_neighbors=n)
    score = cross_val_score(neigh, x , y, cv = folds, scoring = "accuracy").mean()
    cvscore.append(score)
    

In [20]:
knn_score = max(cvscore)
knn_score

0.9800000000000001

In [21]:
optimalk = k_list[cvscore.index(knn_score)]
optimalk

13

In [24]:
classifier = KNeighborsClassifier(n_neighbors=13)
classifier.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=13)

In [25]:
y_pred = classifier.predict(x_test)

## with value 13

In [26]:
from sklearn.metrics import classification_report, confusion_matrix
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        12
Iris-versicolor       1.00      0.86      0.92         7
 Iris-virginica       0.92      1.00      0.96        11

       accuracy                           0.97        30
      macro avg       0.97      0.95      0.96        30
   weighted avg       0.97      0.97      0.97        30

[[12  0  0]
 [ 0  6  1]
 [ 0  0 11]]


In [31]:
classifier.predict([[0.3,0.7,0.5,0.1]])

array(['Iris-versicolor'], dtype=object)

## now our prediction is complete and dump our data in pickle to make api`

In [35]:
import pickle

In [36]:
pickle.dump(classifier, open("iris.sav", "wb"))

In [37]:
data_load = pickle.load(open("iris.sav", "rb"))

In [38]:
data_load

KNeighborsClassifier()